- name: Add apt repository
  apt_repository: repo='ppa:webupd8team/java' state=present update_cache=yes

- name: Accept Oracle license
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    unseen: no
    value: 'true'
    vtype: 'select'

- name: Install Oracle Java 8
  apt: name='oracle-java8-installer' state=present
